Promoting changes to main
merokudao/dApp-Explorer pull request #41
Opened 2024-01-08 04:36 UTC by piyush-bitpack

2024-01-08 05:11 UTC, thebitparticle commented on src/pages/dapp/index.tsx
> +          <p>You have not open or download dapp before posting review.</p>
you have not `opened`

(or) 

You did not visit or download the dapp before to post a review

2024-01-08 05:13 UTC, thebitparticle commented on src/pages/dapp/index.tsx
>          <div className="backdrop-filter backdrop-blur-sm absolute w-full h-full flex items-center justify-center ">
this can be removed now right?

2024-01-08 05:13 UTC, thebitparticle commented on src/pages/dapp/index.tsx
>          <div className="backdrop-filter backdrop-blur-sm absolute w-full h-full flex items-center justify-center ">
this commented block can be removed now right?

2024-01-08 05:14 UTC, thebitparticle requested changes
check the comments please

2024-01-08 08:14 UTC, r4881t approved these changes

2024-01-09 05:07 UTC, piyush-bitpack commented on src/pages/dapp/index.tsx
> +          <p>You have not open or download dapp before posting review.</p>
You have not opened or downloaded Dapp before posting a review.
this will be good.

2024-01-09 06:09 UTC, merged